name: Binaries

on:
  workflow_dispatch: 
  release: 
    types: [released]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    permissions:
      contents: write
      checks: write

      actions: read
      issues: read
      packages: write
      pull-requests: read
      repository-projects: read
      statuses: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: iffy/install-nim@v4
        with:
          version: binary:stable
      - name: Build
        run: |
          sudo apt-get update && sudo apt-get -y upgrade
          sudo apt install -y libvips libvips-tools
          nimble install -d -y
          nimble build 
      - uses: thedoctor0/zip-release@main
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          type: 'zip'
          filename: clutter-linux.zip
          path: clutter
      - uses: thedoctor0/zip-release@main
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          type: 'zip'
          filename: clutter-windows.zip
          path: clutter.exe

      - name: Release
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          asset_paths: '["clutter-*.zip"]'
